name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest

    # Используем ваш кастомный образ как контейнер для всего job
    container:
      image: duyler/php-zts:latest
      options: --user root

    strategy:
      matrix:
        # Если у вас есть разные теги для версий PHP, можно указать их здесь
        php-image: ['duyler/php-zts:latest']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PHP and extensions
        run: |
          php -v
          php -m | grep parallel
          composer --version || echo "Composer not installed"

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

      - name: Run Psalm
        run: vendor/bin/psalm --no-cache

      - name: Run PHP CS Fixer (dry-run)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
